"""superadmin

Revision ID: 30d8bd576471
Revises: f439284ccc62
Create Date: 2026-03-12 11:52:56.995034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d8bd576471'
down_revision: Union[str, Sequence[str], None] = 'f439284ccc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ASSIGNED', 'REJECTED', name='numberrequeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('twilio_phone_number', sa.String(length=20), nullable=True),
    sa.Column('twilio_phone_number_sid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_number_requests_tenant_id'), 'number_requests', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###

    # Add SUPER_ADMIN to userrole so the next migration can insert the superadmin user.
    # Must run in autocommit so it is visible in the next migration's transaction.
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            try:
                op.execute(sa.text("ALTER TYPE userrole ADD VALUE 'SUPER_ADMIN'"))
            except Exception:
                pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_active')
    op.drop_index(op.f('ix_number_requests_tenant_id'), table_name='number_requests')
    op.drop_table('number_requests')
    # ### end Alembic commands ###
