"""Add tenant Twilio phone, booking guest_phone, VoiceCall model

Revision ID: f439284ccc62
Revises: 10a7206a92d4
Create Date: 2026-03-11 06:48:01.998367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f439284ccc62'
down_revision: Union[str, Sequence[str], None] = '10a7206a92d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(length=50), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_booking_id'), 'voice_calls', ['booking_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_call_sid'), 'voice_calls', ['call_sid'], unique=True)
    op.create_index(op.f('ix_voice_calls_tenant_id'), 'voice_calls', ['tenant_id'], unique=False)
    op.add_column('bookings', sa.Column('guest_phone', sa.String(length=20), nullable=True))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tenants', sa.Column('twilio_phone_number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('twilio_phone_number_sid', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tenants_twilio_phone_number'), 'tenants', ['twilio_phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_twilio_phone_number'), table_name='tenants')
    op.drop_column('tenants', 'twilio_phone_number_sid')
    op.drop_column('tenants', 'twilio_phone_number')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'guest_phone')
    op.drop_index(op.f('ix_voice_calls_tenant_id'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_call_sid'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_booking_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    # ### end Alembic commands ###
